# Generated by Django 4.2.2 on 2023-12-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=60)),
                ('conteudo', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='materias',
            name='sala_num',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=5000)),
                ('pdf', models.FileField(upload_to='doc_conteudos', verbose_name='pdf')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_materia', to='educaapp.materias')),
            ],
        ),
    ]
